import React, { useState, useCallback } from 'react';
import {
  View,
  Text,
  FlatList,
  ScrollView,
  ActivityIndicator,
  Pressable,
  TextInput,
  Alert,
  StyleSheet,
  LayoutAnimation,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useLocalSearchParams, useRouter, useFocusEffect } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { colors } from '@/constants/theme';
import { usePlanDetail } from '@/features/plans/hooks/usePlanDetail';
import { usePlans } from '@/features/plans/hooks/usePlans';
import { PlanDaySection } from '@/features/plans/components/PlanDaySection';
import { DaySlotEditor } from '@/features/plans/components/DaySlotEditor';
import type { DaySlot, DaySlotExercise } from '@/features/plans/components/DaySlotEditor';
import { makeTempId } from '@/features/plans/components/DaySlotEditor';
import type { Plan, PlanDay } from '@/features/plans/types';
import { useWorkoutSession } from '@/features/workout/hooks/useWorkoutSession';

/**
 * Convert a Plan's plan_days into DaySlot[] for the DaySlotEditor.
 */
function planToDaySlots(plan: Plan): DaySlot[] {
  return plan.plan_days.map((day) => ({
    tempId: makeTempId(),
    day_name: day.day_name,
    weekday: day.weekday,
    alarmEnabled: day.alarm_enabled ?? false,
    alarmTime: day.alarm_time ?? null,
    exercises: day.plan_day_exercises.map((ex) => ({
      tempId: makeTempId(),
      exercise_id: ex.exercise_id,
      exercise: {
        id: ex.exercise?.id ?? ex.exercise_id,
        name: ex.exercise?.name ?? 'Unknown',
        muscle_groups: (ex.exercise as any)?.muscle_groups,
        equipment: ex.exercise?.equipment ?? 'other',
      },
      target_sets: ex.target_sets.map((s) => ({ ...s })),
      notes: ex.notes,
      unit_override: ex.unit_override,
      weight_progression: ex.weight_progression,
    })),
  }));
}

/**
 * Convert DaySlot[] back into plan_days format for saving.
 */
function daySlotsToplanDays(slots: DaySlot[], planId: string) {
  return slots.map((slot, dayIndex) => ({
    id: '', // new IDs will be generated by Supabase
    plan_id: planId,
    day_name: slot.day_name,
    weekday: slot.weekday,
    alarm_time: slot.alarmEnabled ? slot.alarmTime : null,
    alarm_enabled: slot.alarmEnabled,
    sort_order: dayIndex,
    created_at: new Date().toISOString(),
    plan_day_exercises: slot.exercises.map((ex, exIndex) => ({
      id: '',
      plan_day_id: '',
      exercise_id: ex.exercise_id,
      sort_order: exIndex,
      target_sets: ex.target_sets,
      notes: ex.notes,
      unit_override: ex.unit_override,
      weight_progression: ex.weight_progression,
      created_at: new Date().toISOString(),
      exercise: ex.exercise as any,
    })),
  }));
}

export default function PlanDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const router = useRouter();
  const { plan, isLoading, isSaving, error, refetch, updatePlan } = usePlanDetail(id ?? '');
  const { deletePlan, setActivePlan } = usePlans();
  const { startFromPlan } = useWorkoutSession();

  const [isEditing, setIsEditing] = useState(false);

  // Refetch plan data when screen regains focus (e.g., after tab switch or navigation)
  useFocusEffect(
    useCallback(() => {
      if (!isEditing) refetch();
    }, [refetch, isEditing])
  );
  const [draftName, setDraftName] = useState('');
  const [draftDays, setDraftDays] = useState<DaySlot[]>([]);

  const enterEditMode = useCallback(() => {
    if (!plan) return;
    LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
    // Deep clone via DaySlot conversion (independent copy)
    setDraftName(plan.name);
    setDraftDays(planToDaySlots(plan));
    setIsEditing(true);
  }, [plan]);

  const cancelEdit = useCallback(() => {
    LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
    // Discard draft - no persistence
    setIsEditing(false);
    setDraftName('');
    setDraftDays([]);
  }, []);

  const handleSave = useCallback(async () => {
    if (!plan || !id) return;

    const updatedPlan: Plan = {
      ...JSON.parse(JSON.stringify(plan)),
      name: draftName.trim() || plan.name,
      plan_days: daySlotsToplanDays(draftDays, id),
    };

    const result = await updatePlan(updatedPlan);
    if (result?.success) {
      LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
      setIsEditing(false);
      setDraftName('');
      setDraftDays([]);
    } else {
      Alert.alert('Save Failed', result?.error ?? 'Could not save plan changes.');
    }
  }, [plan, id, draftName, draftDays, updatePlan]);

  const handleDelete = useCallback(() => {
    if (!plan || !id) return;

    Alert.alert(
      `Delete "${plan.name}"?`,
      'Past workouts logged with this plan will be kept.',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete',
          style: 'destructive',
          onPress: async () => {
            try {
              await deletePlan(id);
              router.back();
            } catch (err) {
              Alert.alert('Error', 'Failed to delete plan.');
            }
          },
        },
      ]
    );
  }, [plan, id, deletePlan, router]);

  const handleSetActive = useCallback(async () => {
    if (!id) return;
    try {
      await setActivePlan(id);
    } catch (err) {
      Alert.alert('Error', 'Failed to set plan as active.');
    }
  }, [id, setActivePlan]);

  if (isLoading) {
    return (
      <SafeAreaView style={s.safe} edges={['top']}>
        <View style={s.center}>
          <ActivityIndicator size="large" color={colors.accent} />
        </View>
      </SafeAreaView>
    );
  }

  if (error || !plan) {
    return (
      <SafeAreaView style={s.safe} edges={['top']}>
        <View style={s.header}>
          <Pressable onPress={() => router.back()} hitSlop={8}>
            <Ionicons name="arrow-back" size={24} color={colors.textPrimary} />
          </Pressable>
          <Text style={s.headerTitle}>Plan Not Found</Text>
          <View style={s.headerPlaceholder} />
        </View>
        <View style={s.center}>
          <Text style={s.errorText}>{error ?? 'Plan not found'}</Text>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={s.safe} edges={['top']}>
      {/* Header */}
      <View style={s.header}>
        <Pressable onPress={() => { if (isEditing) cancelEdit(); else router.back(); }} hitSlop={8}>
          <Ionicons
            name={isEditing ? 'close' : 'arrow-back'}
            size={24}
            color={colors.textPrimary}
          />
        </Pressable>

        {isEditing ? (
          <TextInput
            style={s.headerTitleInput}
            value={draftName}
            onChangeText={setDraftName}
            placeholder="Plan name"
            placeholderTextColor={colors.textMuted}
          />
        ) : (
          <View style={s.headerCenter}>
            <Text style={s.headerTitle} numberOfLines={1}>{plan.name}</Text>
            {plan.is_active && (
              <View style={s.activeBadge}>
                <Ionicons name="checkmark-circle" size={14} color={colors.success} />
                <Text style={s.activeBadgeText}>Active Plan</Text>
              </View>
            )}
          </View>
        )}

        {isEditing ? (
          <Pressable
            style={[s.saveBtn, isSaving && s.saveBtnDisabled]}
            onPress={handleSave}
            disabled={isSaving}
          >
            <Text style={s.saveBtnText}>{isSaving ? 'Saving...' : 'Save'}</Text>
          </Pressable>
        ) : (
          <Pressable style={s.editBtn} onPress={enterEditMode}>
            <Text style={s.editBtnText}>Edit</Text>
          </Pressable>
        )}
      </View>

      {/* Content */}
      {isEditing ? (
        <ScrollView
          style={s.scroll}
          contentContainerStyle={s.scrollContent}
          showsVerticalScrollIndicator={false}
          keyboardShouldPersistTaps="handled"
        >
          <DaySlotEditor days={draftDays} onChange={setDraftDays} />
          <Pressable style={s.deleteBtn} onPress={handleDelete}>
            <Ionicons name="trash-outline" size={20} color={colors.error} />
            <Text style={s.deleteBtnText}>Delete Plan</Text>
          </Pressable>
        </ScrollView>
      ) : (
        <FlatList
          data={plan.plan_days}
          keyExtractor={(item) => item.id}
          renderItem={({ item }) => (
            <PlanDaySection day={item} defaultExpanded={true} onStartWorkout={startFromPlan} />
          )}
          contentContainerStyle={s.scrollContent}
          showsVerticalScrollIndicator={false}
          ListEmptyComponent={
            <Text style={s.emptyText}>No days configured</Text>
          }
          ListFooterComponent={
            !plan.is_active ? (
              <Pressable style={s.setActiveBtn} onPress={handleSetActive}>
                <Ionicons name="checkmark-circle-outline" size={20} color={colors.accent} />
                <Text style={s.setActiveText}>Set as Active Plan</Text>
              </Pressable>
            ) : null
          }
        />
      )}
    </SafeAreaView>
  );
}

const s = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceElevated,
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
    marginHorizontal: 12,
  },
  headerTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  headerTitleInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
    marginHorizontal: 12,
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: colors.accent,
  },
  headerPlaceholder: {
    width: 50,
  },
  editBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: colors.surfaceElevated,
  },
  editBtnText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  saveBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: colors.accent,
  },
  saveBtnDisabled: {
    opacity: 0.5,
  },
  saveBtnText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '600',
  },
  activeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 2,
  },
  activeBadgeText: {
    color: colors.success,
    fontSize: 13,
    fontWeight: '600',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorText: {
    color: colors.error,
    fontSize: 16,
  },
  emptyText: {
    color: colors.textMuted,
    fontSize: 15,
    textAlign: 'center',
    marginTop: 40,
  },
  setActiveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    marginTop: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.accent,
  },
  setActiveText: {
    color: colors.accent,
    fontSize: 15,
    fontWeight: '600',
  },
  deleteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    marginTop: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.error,
  },
  deleteBtnText: {
    color: colors.error,
    fontSize: 15,
    fontWeight: '600',
  },
});
